### ISSUE TITLE
Change Service Name

### ISSUE THREAD

**Issue by a-ddollar-cs** [a-ddollar-cs/Plomo#3]

**Comment by rahulvaddepalli2** [comment]
Modified the following properties in the 'ignition.conf' file:
- wrapper.name=Ignition -> wrapper.name=Inception
- wrapper.displayname=Ignition -> wrapper.displayname=Inception
- wrapper.description=Ignition Gateway -> wrapper.description=Inception Gateway

Also changed the service name on the Linux VM from Ignition-Gateway.service ->Inception.service
