### ISSUE TITLE
Remote Tag Provider to GW1

### ISSUE THREAD

**Issue by a-ddollar-cs** [a-ddollar-cs/Plomo#8]

**Comment by lorenshadi98** [comment]
.

**Comment by lorenshadi98** [comment]
Start time: 3:31 pm
End time: 3:45pm
Notes:
Created GAN connection from GW1 to GW2
Created Real time remote tag provider in GW1 pointing to Edge gateway (GW2).
Tried to create a remote tag provider without GAN connection, but was getting Service Unavailable errors.
